import type { Metadata } from "next";
import Link from "next/link";
import { LogoMark } from "@/components/app-preview";

export const metadata: Metadata = { title: "Atten vs cloud TTS | ElevenLabs, Speechify, and local speech", description: "Understand when to choose Atten's free local text-to-speech over hosted services such as ElevenLabs or Speechify." };

const rows = [["Where speech runs", "On your Mac or Windows PC", "On a provider's cloud infrastructure"], ["Works offline", "Yes, after installation", "Usually requires an internet connection"], ["Text privacy", "Text stays on your computer", "Text is sent to a hosted service for processing"], ["Pricing shape", "Free and open source", "Typically plan, usage, or feature based"], ["Best for", "Private, offline, repeatable local workflows", "Managed cloud workflows and hosted voice services"], ["Automation", "Desktop app plus command-line interface", "Provider API or product-specific integrations"]];

export default function ComparePage() { return <main className="min-h-screen bg-[#080807] text-[#e7eef8]"><header className="mx-auto flex max-w-6xl items-center justify-between px-5 py-5 sm:px-8"><Link href="/" className="flex items-center gap-2.5"><LogoMark small/><span className="mono text-[11px] font-bold tracking-[.25em]">ATTEN</span></Link><Link href="/" className="text-sm text-[#8fa2ba] hover:text-[#5ddbff]">← Back to home</Link></header><div className="mx-auto max-w-6xl px-5 pb-24 pt-16 sm:px-8 sm:pt-24"><p className="mono text-[10px] tracking-[.22em] text-[#5ddbff]">CHOOSE YOUR TTS WORKFLOW</p><h1 className="mt-5 max-w-4xl text-5xl font-semibold tracking-[-.06em] text-white sm:text-7xl">Atten vs cloud text-to-speech.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-[#a7b6cc]">There is no universal best TTS tool. Atten is the clear choice when the important part is that generation happens locally, privately, and without a recurring bill.</p><div className="mt-14 overflow-x-auto rounded-2xl border border-white/10"><table className="w-full min-w-[680px] border-collapse text-left text-sm"><thead><tr className="bg-[#0e1726] text-white"><th className="w-1/3 p-5 font-semibold">Decision point</th><th className="w-1/3 border-l border-white/10 p-5 font-semibold text-[#91e8ff]">Atten</th><th className="w-1/3 border-l border-white/10 p-5 font-semibold">Hosted TTS services</th></tr></thead><tbody>{rows.map(([point, atten, cloud]) => <tr key={point} className="border-t border-white/10"><th className="p-5 font-medium text-[#c8d6e8]">{point}</th><td className="border-l border-white/10 p-5 leading-6 text-[#9eeaff]">{atten}</td><td className="border-l border-white/10 p-5 leading-6 text-[#8fa2ba]">{cloud}</td></tr>)}</tbody></table></div><div className="mt-14 grid gap-4 md:grid-cols-3"><article className="rounded-2xl border border-white/10 bg-[#0a101b] p-6"><h2 className="font-semibold text-white">Choose Atten for privacy</h2><p className="mt-3 text-sm leading-6 text-[#8fa2ba]">Keep drafts, documents, scripts, and generated audio on your own computer.</p></article><article className="rounded-2xl border border-white/10 bg-[#0a101b] p-6"><h2 className="font-semibold text-white">Choose Atten for cost</h2><p className="mt-3 text-sm leading-6 text-[#8fa2ba]">Generate locally without a subscription or usage meter.</p></article><article className="rounded-2xl border border-white/10 bg-[#0a101b] p-6"><h2 className="font-semibold text-white">Choose cloud when needed</h2><p className="mt-3 text-sm leading-6 text-[#8fa2ba]">A hosted provider may suit you better if you need a managed API or a broad commercial voice marketplace.</p></article></div><div className="mt-14 text-center"><a href="https://github.com/jashdubal/atten/releases/latest" className="inline-flex rounded-xl bg-[#5ddbff] px-5 py-3.5 font-semibold text-[#061018] shadow-[0_16px_50px_rgba(93,219,255,.2)]">Download Atten</a></div></div></main>; }
